export function generateReadableTextFromHTML(html: string): string {
  html = html.replace(/<body>/g, '').replace(/<\/body>/g, '')
  html = html.replace(/<html>/g, '').replace(/<\/html>/g, '')
  html = html.replace(/<article>/g, '').replace(/<\/article>/g, '')
  html = html.replace(/<section>/g, '').replace(/<\/section>/g, '')
  html = html.replace(/<div>/g, '').replace(/<\/div>/g, '')
  html = html.replace(/<span>/g, '').replace(/<\/span>/g, '')
  html = html.replace(/<header>/g, '').replace(/<\/header>/g, '')
  html = html.replace(/<footer>/g, '').replace(/<\/footer>/g, '')
  html = html.replace(/<nav>/g, '').replace(/<\/nav>/g, '')
  html = html.replace(/<aside>/g, '').replace(/<\/aside>/g, '')
  html = html.replace(/<figure>/g, '').replace(/<\/figure>/g, '')
  html = html.replace(/<figcaption>/g, '').replace(/<\/figcaption>/g, '')
  html = html.replace(/<table>/g, '').replace(/<\/table>/g, '')
  html = html.replace(/<thead>/g, '').replace(/<\/thead>/g, '')
  html = html.replace(/<tbody>/g, '').replace(/<\/tbody>/g, '')
  html = html.replace(/<tfoot>/g, '').replace(/<\/tfoot>/g, '')
  html = html.replace(/<tr>/g, '').replace(/<\/tr>/g, '')
  html = html.replace(/<th>/g, '').replace(/<\/th>/g, '')
  html = html.replace(/<td>/g, '').replace(/<\/td>/g, '')
  html = html.replace(/<blockquote>/g, '').replace(/<\/blockquote>/g, '')
  html = html.replace(/<cite>/g, '').replace(/<\/cite>/g, '')
  html = html.replace(/<q>/g, '').replace(/<\/q>/g, '')
  html = html.replace(/<abbr>/g, '').replace(/<\/abbr>/g, '')
  html = html.replace(/<address>/g, '').replace(/<\/address>/g, '')

  html = html.replace(/<em>/g, 'Emphasized ').replace(/<\/em>/g, '\n')
  html = html.replace(/<i>/g, 'Italic ').replace(/<\/i>/g, '\n')
  html = html.replace(/<strong>/g, 'Bold ').replace(/<\/strong>/g, '\n')

  html = html.replace(/<h1>/g, 'Heading 1: ').replace(/<\/h1>/g, '\n')
  html = html.replace(/<h2>/g, 'Heading 2: ').replace(/<\/h2>/g, '\n')
  html = html.replace(/<h3>/g, 'Heading 3: ').replace(/<\/h3>/g, '\n')
  html = html.replace(/<h4>/g, 'Heading 4: ').replace(/<\/h4>/g, '\n')
  html = html.replace(/<h5>/g, 'Heading 5: ').replace(/<\/h5>/g, '\n')
  html = html.replace(/<h6>/g, 'Heading 6: ').replace(/<\/h6>/g, '\n')
  html = html.replace(/<p>/g, 'Paragraph: ').replace(/<\/p>/g, '\n')
  html = html.replace(/<ul>/g, 'Unordered List\n').replace(/<\/ul>/g, '\n')
  html = html.replace(/<ol>/g, 'Ordered List\n').replace(/<\/ol>/g, '\n')
  html = html.replace(/<li>/g, 'List Item ').replace(/<\/li>/g, '\n')
  html = html
    .replace(/<br>/g, '')
    .replace(/<\/br>/g, '')
    .replace(/<br\/>/g, '')
  return html
}
